### ISSUE TITLE
no hmmersearch for summarize-metabolism

### ISSUE THREAD

**Issue by Thexiyang** [elizabethmcd/metabolisHMM#40] opened 2019-12-22 10:33 UTC
Hi! Thanks for the tool. I installed the software using the conda way. For `summarize-metabolism` workflow, it did not perform `hmmsearch` (empty files for out folder); while `search-custom-markers` workflow did that. Could you check if there is any issue with the `summarize-metabolism` script? Here is my cmd line: `summarize-metabolism --input faa --output summaries --metadata ../genomeinfo.csv  --aggregate ON`. Thanks!

**Comment by elizabethmcd** [comment] 2019-12-23 03:07
Thanks for trying the tool out! I will double check that workflow. Did you get any errors associated with not getting any output?

**Comment by elizabethmcd** [comment] 2019-12-23 03:14
I'm going to guess this might be due to how the workflow checks for the curated markers as brought up in issue #41. I'll be making a fix to that workflow and a couple other things and try and get a new version pushed out within a couple of days.

**Comment by Thexiyang** [comment] 2019-12-23 03:59
Thanks for the reply. There is no error message shown but empty files and it went to the end with production of a heatmap (all markers read as zero). The issue 41 did happen to me. But when I downloaded the curated markers and run the workflow in this file as the working file, the software could find the makers itself without reporting any error.

**Comment by elizabethmcd** [comment] 2019-12-23 04:02
Oh you ran the workflow from within the `curated_markers` folder so it knew where to find `metabolic_markers`. Interesting that hmmsearch worked for the custom workflow but not this one. Will check on this tomorrow. Unless it's how you're defining your input folder... can you try adding a slash to the end of the faa folder like `faa/`? I doubt this is the issue but worth trying.

**Comment by Thexiyang** [comment] 2019-12-23 04:22
It should not be due to this, as it indeed performed reformatting procedure. Anyway, I just tried as you suggested, same results.

**Comment by elizabethmcd** [comment] 2019-12-23 17:15
I just pushed version 2.1 to PyPi, so if you could update with `python3 -m pip install metabolisHMM --upgrade` you should get the newest version and see if that fixes things.

**Comment by Thexiyang** [comment] 2019-12-24 08:16
Thanks! It indeed solved the issue. but there is still one like issue #41. If I used the flag` --aggregate ON`, then it came across the same error message: ValueError: zero-size array to reduction operation minimum which has no identity. I guess it may have something related how to prepare the csv files. Could you make a template file in the github files?

**Comment by elizabethmcd** [comment] 2019-12-24 16:29
There is a template in the aquifer demo tutorial. What does your CSV file look like?
Does this error only happen if you have the aggregate option ON? What happens if you turn it OFF?

**Comment by Thexiyang** [comment] 2019-12-25 14:35
My CSV file exactly looks like your template. When it was turned off, it is good; but when it was on , it showed the error message.

**Comment by elizabethmcd** [comment] 2020-01-09 22:52
I have been unable to reproduce this error on my system. See the latest comment of issue #41 for further information. I'm going to close this issue as now it is redundant with the other issue and I will continue troubleshooting there.

**Closed as completed by elizabethmcd** 2020-01-09 22:52 UTC
